server:
  port: 9092
  
eureka:
  instance:
    hostname: ms-naming-server-2
  client:
    serviceUrl: 
      defaultZone: http://ms-naming-server-1:9091/eureka/,http://ms-naming-server-3:9093/eureka/
